"""
Describes which database tables should be visible in the admin pages and
further, how those fields should be represented.
"""

from django.contrib import admin
from .models import Campaign, Location, Encounter, Item, Creature, PlotMoment, Note, Skill, Tool, WeaponProperty, Map, CreatureInstance, UserCampaign, UserLocation, UserEncounter, UserItem, UserCreature, UserNote, UserMap, CampaignMap, CampaignLocation, CampaignEncounter, CampaignItem, CampaignCreature, CampaignPlotMoment, LocationMap, LocationEncounter, LocationItem, LocationCreature, LocationPlotMoment, EncounterItem, EncounterCreature, EncounterPlotMoment, ItemCreature, ItemPlotMoment, ItemWeaponProperty, CreaturePlotMoment, CreatureSkillProficiency, CreatureToolProficiency, NoteCampaign, NoteLocation, NoteEncounter, NoteItem, NoteCreature, NotePlotMoment

admin.site.register(Campaign)
admin.site.register(Location)
admin.site.register(Encounter)
admin.site.register(Item)
admin.site.register(Creature)
admin.site.register(PlotMoment)
admin.site.register(Note)
admin.site.register(Skill)
admin.site.register(Tool)
admin.site.register(WeaponProperty)
admin.site.register(Map)
admin.site.register(CreatureInstance)
admin.site.register(UserCampaign)
admin.site.register(UserLocation)
admin.site.register(UserEncounter)
admin.site.register(UserItem)
admin.site.register(UserCreature)
admin.site.register(UserNote)
admin.site.register(UserMap)
admin.site.register(CampaignMap)
admin.site.register(CampaignLocation)
admin.site.register(CampaignEncounter)
admin.site.register(CampaignItem)
admin.site.register(CampaignCreature)
admin.site.register(CampaignPlotMoment)
admin.site.register(LocationMap)
admin.site.register(LocationEncounter)
admin.site.register(LocationItem)
admin.site.register(LocationCreature)
admin.site.register(LocationPlotMoment)
admin.site.register(EncounterItem)
admin.site.register(EncounterCreature)
admin.site.register(EncounterPlotMoment)
admin.site.register(ItemCreature)
admin.site.register(ItemPlotMoment)
admin.site.register(ItemWeaponProperty)
admin.site.register(CreaturePlotMoment)
admin.site.register(CreatureSkillProficiency)
admin.site.register(CreatureToolProficiency)
admin.site.register(NoteCampaign)
admin.site.register(NoteLocation)
admin.site.register(NoteEncounter)
admin.site.register(NoteItem)
admin.site.register(NoteCreature)
admin.site.register(NotePlotMoment)
